add babel-plugin-transform-object-rest-spread
required by honeycomb-web-toolkit

previously the build was giving this error:
> honeycomb-website@0.0.0 js C:\web\honeycomb
> browserify -t [babelify] src/assets/js/site.js | uglifyjs > dist/assets/js/site.min.js && echo 'JS compiled'

ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "C:\\web\\honeycomb\\node_modules\\honeycomb-web-toolkit\\.babelrc" at 0, attempted to resolve relative to "C:\\web\\honeycomb\\node_modules\\honeycomb-web-toolkit" while parsing file: C:\web\honeycomb\node_modules\honeycomb-web-toolkit\src\browser\js\honeycomb.browser.js